export const FETCH_TVS_STARTED = 'FETCH_TVS_STARTED';
export const FETCH_TVS_SUCCEEDED = 'FETCH_TVS_SUCCEEDED';
export const FETCH_TVS_FAILED = 'FETCH_TVS_FAILED';

export const SAVE_TV_SUCCEEDED = 'SAVE_TV_SUCCEEDED';
export const SAVE_TV_FAILED = 'SAVE_TV_FAILED';
export const SAVE_TV_STARTED = 'SAVE_TV_STARTED';

export const DELETE_TV_SUCCEEDED = 'DELETE_TV_SUCCEEDED';
export const DELETE_TV_FAILED = 'DELETE_TV_FAILED';
export const DELETE_TV_STARTED = 'DELETE_TV_STARTED';

export const SET_PAGE = 'SET_PAGE';
export const SET_SEARCH = 'SET_SEARCH';
